#!/bin/bash

cd $(dirname $0)

PYTHON=python3

build_pre()
{
    if command -v protoc >/dev/null 2>&1; then
        protoc --go_out=plugins=grpc:./etcdadmind/pb/etcdadminpb -I./proto etcdadmin.proto
    elif ${PYTHON} -m grpc_tools.protoc >/dev/null 2>&1; then
        ${PYTHON} -m grpc_tools.protoc \
                --go_out=plugins=grpc:./etcdadmind/pb/etcdadminpb -I./proto etcdadmin.proto
    else
        echo "err: command protoc or grpc_tools.protoc module of ${PYTHON} not found"
        exit 1
    fi
}

contrib()
{
    [ -d /etc/etcdadmin ] && rm -rf /etcd/etcdadmin
    mkdir -p /etc/etcdadmin
    cp -f etcdadmind/etcdadmind.conf /etc/etcdadmin/
}


uncontrib()
{
    [ -d /etc/etcdadmin ] && rm -rf /etc/etcdadmin
}


if [ x"$1" == x"build-pre" ]; then
    build_pre
elif [ x"$1" == x"contrib" ]; then
    contrib
elif [ x"$1" == x"uncontrib" ]; then
    uncontrib
fi

exit $?
