// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.12.3
// source: etcdadmin.proto

package etcdadminpb

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Retcode int32

const (
	Retcode_OK   Retcode = 0 // ok
	Retcode_FAIL Retcode = 1 // fail
)

// Enum value maps for Retcode.
var (
	Retcode_name = map[int32]string{
		0: "OK",
		1: "FAIL",
	}
	Retcode_value = map[string]int32{
		"OK":   0,
		"FAIL": 1,
	}
)

func (x Retcode) Enum() *Retcode {
	p := new(Retcode)
	*p = x
	return p
}

func (x Retcode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Retcode) Descriptor() protoreflect.EnumDescriptor {
	return file_etcdadmin_proto_enumTypes[0].Descriptor()
}

func (Retcode) Type() protoreflect.EnumType {
	return &file_etcdadmin_proto_enumTypes[0]
}

func (x Retcode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Retcode.Descriptor instead.
func (Retcode) EnumDescriptor() ([]byte, []int) {
	return file_etcdadmin_proto_rawDescGZIP(), []int{0}
}

type EtcdCmd int32

const (
	EtcdCmd_NONE    EtcdCmd = 0 // none
	EtcdCmd_STOP    EtcdCmd = 1 // stop
	EtcdCmd_START   EtcdCmd = 2 // start
	EtcdCmd_RESTART EtcdCmd = 3 // restart
)

// Enum value maps for EtcdCmd.
var (
	EtcdCmd_name = map[int32]string{
		0: "NONE",
		1: "STOP",
		2: "START",
		3: "RESTART",
	}
	EtcdCmd_value = map[string]int32{
		"NONE":    0,
		"STOP":    1,
		"START":   2,
		"RESTART": 3,
	}
)

func (x EtcdCmd) Enum() *EtcdCmd {
	p := new(EtcdCmd)
	*p = x
	return p
}

func (x EtcdCmd) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EtcdCmd) Descriptor() protoreflect.EnumDescriptor {
	return file_etcdadmin_proto_enumTypes[1].Descriptor()
}

func (EtcdCmd) Type() protoreflect.EnumType {
	return &file_etcdadmin_proto_enumTypes[1]
}

func (x EtcdCmd) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EtcdCmd.Descriptor instead.
func (EtcdCmd) EnumDescriptor() ([]byte, []int) {
	return file_etcdadmin_proto_rawDescGZIP(), []int{1}
}

type ManagerEtcdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cmd      EtcdCmd                      `protobuf:"varint,1,opt,name=cmd,proto3,enum=etcdadminpb.EtcdCmd" json:"cmd,omitempty"`
	Clearwal bool                         `protobuf:"varint,2,opt,name=clearwal,proto3" json:"clearwal,omitempty"`
	Cfgs     []*ManagerEtcdRequest_Config `protobuf:"bytes,3,rep,name=cfgs,proto3" json:"cfgs,omitempty"`
}

func (x *ManagerEtcdRequest) Reset() {
	*x = ManagerEtcdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_etcdadmin_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ManagerEtcdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManagerEtcdRequest) ProtoMessage() {}

func (x *ManagerEtcdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_etcdadmin_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManagerEtcdRequest.ProtoReflect.Descriptor instead.
func (*ManagerEtcdRequest) Descriptor() ([]byte, []int) {
	return file_etcdadmin_proto_rawDescGZIP(), []int{0}
}

func (x *ManagerEtcdRequest) GetCmd() EtcdCmd {
	if x != nil {
		return x.Cmd
	}
	return EtcdCmd_NONE
}

func (x *ManagerEtcdRequest) GetClearwal() bool {
	if x != nil {
		return x.Clearwal
	}
	return false
}

func (x *ManagerEtcdRequest) GetCfgs() []*ManagerEtcdRequest_Config {
	if x != nil {
		return x.Cfgs
	}
	return nil
}

type ManagerEtcdReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Errcode Retcode `protobuf:"varint,1,opt,name=errcode,proto3,enum=etcdadminpb.Retcode" json:"errcode,omitempty"`
	Errmsg  string  `protobuf:"bytes,2,opt,name=errmsg,proto3" json:"errmsg,omitempty"`
}

func (x *ManagerEtcdReply) Reset() {
	*x = ManagerEtcdReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_etcdadmin_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ManagerEtcdReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManagerEtcdReply) ProtoMessage() {}

func (x *ManagerEtcdReply) ProtoReflect() protoreflect.Message {
	mi := &file_etcdadmin_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManagerEtcdReply.ProtoReflect.Descriptor instead.
func (*ManagerEtcdReply) Descriptor() ([]byte, []int) {
	return file_etcdadmin_proto_rawDescGZIP(), []int{1}
}

func (x *ManagerEtcdReply) GetErrcode() Retcode {
	if x != nil {
		return x.Errcode
	}
	return Retcode_OK
}

func (x *ManagerEtcdReply) GetErrmsg() string {
	if x != nil {
		return x.Errmsg
	}
	return ""
}

type AddMemberRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Member *AddMemberRequest_Member `protobuf:"bytes,1,opt,name=member,proto3" json:"member,omitempty"`
}

func (x *AddMemberRequest) Reset() {
	*x = AddMemberRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_etcdadmin_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddMemberRequest) ProtoMessage() {}

func (x *AddMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_etcdadmin_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddMemberRequest.ProtoReflect.Descriptor instead.
func (*AddMemberRequest) Descriptor() ([]byte, []int) {
	return file_etcdadmin_proto_rawDescGZIP(), []int{2}
}

func (x *AddMemberRequest) GetMember() *AddMemberRequest_Member {
	if x != nil {
		return x.Member
	}
	return nil
}

type AddMemberReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Errcode Retcode `protobuf:"varint,1,opt,name=errcode,proto3,enum=etcdadminpb.Retcode" json:"errcode,omitempty"`
	Errmsg  string  `protobuf:"bytes,2,opt,name=errmsg,proto3" json:"errmsg,omitempty"`
}

func (x *AddMemberReply) Reset() {
	*x = AddMemberReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_etcdadmin_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddMemberReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddMemberReply) ProtoMessage() {}

func (x *AddMemberReply) ProtoReflect() protoreflect.Message {
	mi := &file_etcdadmin_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddMemberReply.ProtoReflect.Descriptor instead.
func (*AddMemberReply) Descriptor() ([]byte, []int) {
	return file_etcdadmin_proto_rawDescGZIP(), []int{3}
}

func (x *AddMemberReply) GetErrcode() Retcode {
	if x != nil {
		return x.Errcode
	}
	return Retcode_OK
}

func (x *AddMemberReply) GetErrmsg() string {
	if x != nil {
		return x.Errmsg
	}
	return ""
}

type ListMemberRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListMemberRequest) Reset() {
	*x = ListMemberRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_etcdadmin_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMemberRequest) ProtoMessage() {}

func (x *ListMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_etcdadmin_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMemberRequest.ProtoReflect.Descriptor instead.
func (*ListMemberRequest) Descriptor() ([]byte, []int) {
	return file_etcdadmin_proto_rawDescGZIP(), []int{4}
}

type ListMemberReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Errcode Retcode                   `protobuf:"varint,1,opt,name=errcode,proto3,enum=etcdadminpb.Retcode" json:"errcode,omitempty"`
	Errmsg  string                    `protobuf:"bytes,2,opt,name=errmsg,proto3" json:"errmsg,omitempty"`
	Members []*ListMemberReply_Member `protobuf:"bytes,3,rep,name=members,proto3" json:"members,omitempty"`
}

func (x *ListMemberReply) Reset() {
	*x = ListMemberReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_etcdadmin_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListMemberReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMemberReply) ProtoMessage() {}

func (x *ListMemberReply) ProtoReflect() protoreflect.Message {
	mi := &file_etcdadmin_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMemberReply.ProtoReflect.Descriptor instead.
func (*ListMemberReply) Descriptor() ([]byte, []int) {
	return file_etcdadmin_proto_rawDescGZIP(), []int{5}
}

func (x *ListMemberReply) GetErrcode() Retcode {
	if x != nil {
		return x.Errcode
	}
	return Retcode_OK
}

func (x *ListMemberReply) GetErrmsg() string {
	if x != nil {
		return x.Errmsg
	}
	return ""
}

func (x *ListMemberReply) GetMembers() []*ListMemberReply_Member {
	if x != nil {
		return x.Members
	}
	return nil
}

type RemoveMemberRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *RemoveMemberRequest) Reset() {
	*x = RemoveMemberRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_etcdadmin_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveMemberRequest) ProtoMessage() {}

func (x *RemoveMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_etcdadmin_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveMemberRequest.ProtoReflect.Descriptor instead.
func (*RemoveMemberRequest) Descriptor() ([]byte, []int) {
	return file_etcdadmin_proto_rawDescGZIP(), []int{6}
}

func (x *RemoveMemberRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type RemoveMemberReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Errcode Retcode `protobuf:"varint,1,opt,name=errcode,proto3,enum=etcdadminpb.Retcode" json:"errcode,omitempty"`
	Errmsg  string  `protobuf:"bytes,2,opt,name=errmsg,proto3" json:"errmsg,omitempty"`
}

func (x *RemoveMemberReply) Reset() {
	*x = RemoveMemberReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_etcdadmin_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveMemberReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveMemberReply) ProtoMessage() {}

func (x *RemoveMemberReply) ProtoReflect() protoreflect.Message {
	mi := &file_etcdadmin_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveMemberReply.ProtoReflect.Descriptor instead.
func (*RemoveMemberReply) Descriptor() ([]byte, []int) {
	return file_etcdadmin_proto_rawDescGZIP(), []int{7}
}

func (x *RemoveMemberReply) GetErrcode() Retcode {
	if x != nil {
		return x.Errcode
	}
	return Retcode_OK
}

func (x *RemoveMemberReply) GetErrmsg() string {
	if x != nil {
		return x.Errmsg
	}
	return ""
}

type ManagerEtcdRequest_Config struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *ManagerEtcdRequest_Config) Reset() {
	*x = ManagerEtcdRequest_Config{}
	if protoimpl.UnsafeEnabled {
		mi := &file_etcdadmin_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ManagerEtcdRequest_Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManagerEtcdRequest_Config) ProtoMessage() {}

func (x *ManagerEtcdRequest_Config) ProtoReflect() protoreflect.Message {
	mi := &file_etcdadmin_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManagerEtcdRequest_Config.ProtoReflect.Descriptor instead.
func (*ManagerEtcdRequest_Config) Descriptor() ([]byte, []int) {
	return file_etcdadmin_proto_rawDescGZIP(), []int{0, 0}
}

func (x *ManagerEtcdRequest_Config) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ManagerEtcdRequest_Config) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type AddMemberRequest_Member struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Ip   string `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
}

func (x *AddMemberRequest_Member) Reset() {
	*x = AddMemberRequest_Member{}
	if protoimpl.UnsafeEnabled {
		mi := &file_etcdadmin_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddMemberRequest_Member) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddMemberRequest_Member) ProtoMessage() {}

func (x *AddMemberRequest_Member) ProtoReflect() protoreflect.Message {
	mi := &file_etcdadmin_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddMemberRequest_Member.ProtoReflect.Descriptor instead.
func (*AddMemberRequest_Member) Descriptor() ([]byte, []int) {
	return file_etcdadmin_proto_rawDescGZIP(), []int{2, 0}
}

func (x *AddMemberRequest_Member) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AddMemberRequest_Member) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

type ListMemberReply_Member struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Ip   string `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
}

func (x *ListMemberReply_Member) Reset() {
	*x = ListMemberReply_Member{}
	if protoimpl.UnsafeEnabled {
		mi := &file_etcdadmin_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListMemberReply_Member) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMemberReply_Member) ProtoMessage() {}

func (x *ListMemberReply_Member) ProtoReflect() protoreflect.Message {
	mi := &file_etcdadmin_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMemberReply_Member.ProtoReflect.Descriptor instead.
func (*ListMemberReply_Member) Descriptor() ([]byte, []int) {
	return file_etcdadmin_proto_rawDescGZIP(), []int{5, 0}
}

func (x *ListMemberReply_Member) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ListMemberReply_Member) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

var File_etcdadmin_proto protoreflect.FileDescriptor

var file_etcdadmin_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x65, 0x74, 0x63, 0x64, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x0b, 0x65, 0x74, 0x63, 0x64, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x70, 0x62, 0x22, 0xc6,
	0x01, 0x0a, 0x12, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x45, 0x74, 0x63, 0x64, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x26, 0x0a, 0x03, 0x63, 0x6d, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x14, 0x2e, 0x65, 0x74, 0x63, 0x64, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x70, 0x62,
	0x2e, 0x45, 0x74, 0x63, 0x64, 0x43, 0x6d, 0x64, 0x52, 0x03, 0x63, 0x6d, 0x64, 0x12, 0x1a, 0x0a,
	0x08, 0x63, 0x6c, 0x65, 0x61, 0x72, 0x77, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x08, 0x63, 0x6c, 0x65, 0x61, 0x72, 0x77, 0x61, 0x6c, 0x12, 0x3a, 0x0a, 0x04, 0x63, 0x66, 0x67,
	0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x65, 0x74, 0x63, 0x64, 0x61, 0x64,
	0x6d, 0x69, 0x6e, 0x70, 0x62, 0x2e, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x45, 0x74, 0x63,
	0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52,
	0x04, 0x63, 0x66, 0x67, 0x73, 0x1a, 0x30, 0x0a, 0x06, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12,
	0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65,
	0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x5a, 0x0a, 0x10, 0x4d, 0x61, 0x6e, 0x61, 0x67,
	0x65, 0x72, 0x45, 0x74, 0x63, 0x64, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x2e, 0x0a, 0x07, 0x65,
	0x72, 0x72, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x14, 0x2e, 0x65,
	0x74, 0x63, 0x64, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x74, 0x63, 0x6f,
	0x64, 0x65, 0x52, 0x07, 0x65, 0x72, 0x72, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x65,
	0x72, 0x72, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x65, 0x72, 0x72,
	0x6d, 0x73, 0x67, 0x22, 0x7e, 0x0a, 0x10, 0x41, 0x64, 0x64, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x3c, 0x0a, 0x06, 0x6d, 0x65, 0x6d, 0x62, 0x65,
	0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x65, 0x74, 0x63, 0x64, 0x61, 0x64,
	0x6d, 0x69, 0x6e, 0x70, 0x62, 0x2e, 0x41, 0x64, 0x64, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x06, 0x6d,
	0x65, 0x6d, 0x62, 0x65, 0x72, 0x1a, 0x2c, 0x0a, 0x06, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x70, 0x22, 0x58, 0x0a, 0x0e, 0x41, 0x64, 0x64, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x2e, 0x0a, 0x07, 0x65, 0x72, 0x72, 0x63, 0x6f, 0x64, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x14, 0x2e, 0x65, 0x74, 0x63, 0x64, 0x61, 0x64, 0x6d,
	0x69, 0x6e, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x74, 0x63, 0x6f, 0x64, 0x65, 0x52, 0x07, 0x65, 0x72,
	0x72, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x65, 0x72, 0x72, 0x6d, 0x73, 0x67, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x65, 0x72, 0x72, 0x6d, 0x73, 0x67, 0x22, 0x13, 0x0a,
	0x11, 0x4c, 0x69, 0x73, 0x74, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x22, 0xc6, 0x01, 0x0a, 0x0f, 0x4c, 0x69, 0x73, 0x74, 0x4d, 0x65, 0x6d, 0x62, 0x65,
	0x72, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x2e, 0x0a, 0x07, 0x65, 0x72, 0x72, 0x63, 0x6f, 0x64,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x14, 0x2e, 0x65, 0x74, 0x63, 0x64, 0x61, 0x64,
	0x6d, 0x69, 0x6e, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x74, 0x63, 0x6f, 0x64, 0x65, 0x52, 0x07, 0x65,
	0x72, 0x72, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x65, 0x72, 0x72, 0x6d, 0x73, 0x67,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x65, 0x72, 0x72, 0x6d, 0x73, 0x67, 0x12, 0x3d,
	0x0a, 0x07, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x23, 0x2e, 0x65, 0x74, 0x63, 0x64, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x70, 0x62, 0x2e, 0x4c, 0x69,
	0x73, 0x74, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x2e, 0x4d, 0x65,
	0x6d, 0x62, 0x65, 0x72, 0x52, 0x07, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x1a, 0x2c, 0x0a,
	0x06, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x70, 0x22, 0x29, 0x0a, 0x13, 0x52,
	0x65, 0x6d, 0x6f, 0x76, 0x65, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x5b, 0x0a, 0x11, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65,
	0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x2e, 0x0a, 0x07, 0x65,
	0x72, 0x72, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x14, 0x2e, 0x65,
	0x74, 0x63, 0x64, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x74, 0x63, 0x6f,
	0x64, 0x65, 0x52, 0x07, 0x65, 0x72, 0x72, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x65,
	0x72, 0x72, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x65, 0x72, 0x72,
	0x6d, 0x73, 0x67, 0x2a, 0x1b, 0x0a, 0x07, 0x52, 0x65, 0x74, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x06,
	0x0a, 0x02, 0x4f, 0x4b, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x46, 0x41, 0x49, 0x4c, 0x10, 0x01,
	0x2a, 0x35, 0x0a, 0x07, 0x45, 0x74, 0x63, 0x64, 0x43, 0x6d, 0x64, 0x12, 0x08, 0x0a, 0x04, 0x4e,
	0x4f, 0x4e, 0x45, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x53, 0x54, 0x4f, 0x50, 0x10, 0x01, 0x12,
	0x09, 0x0a, 0x05, 0x53, 0x54, 0x41, 0x52, 0x54, 0x10, 0x02, 0x12, 0x0b, 0x0a, 0x07, 0x52, 0x45,
	0x53, 0x54, 0x41, 0x52, 0x54, 0x10, 0x03, 0x32, 0xdd, 0x02, 0x0a, 0x0d, 0x47, 0x72, 0x70, 0x63,
	0x45, 0x74, 0x63, 0x64, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x12, 0x53, 0x0a, 0x0f, 0x47, 0x72, 0x70,
	0x63, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x45, 0x74, 0x63, 0x64, 0x12, 0x1f, 0x2e, 0x65,
	0x74, 0x63, 0x64, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x70, 0x62, 0x2e, 0x4d, 0x61, 0x6e, 0x61, 0x67,
	0x65, 0x72, 0x45, 0x74, 0x63, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e,
	0x65, 0x74, 0x63, 0x64, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x70, 0x62, 0x2e, 0x4d, 0x61, 0x6e, 0x61,
	0x67, 0x65, 0x72, 0x45, 0x74, 0x63, 0x64, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x4d,
	0x0a, 0x0d, 0x47, 0x72, 0x70, 0x63, 0x41, 0x64, 0x64, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x12,
	0x1d, 0x2e, 0x65, 0x74, 0x63, 0x64, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x70, 0x62, 0x2e, 0x41, 0x64,
	0x64, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b,
	0x2e, 0x65, 0x74, 0x63, 0x64, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x70, 0x62, 0x2e, 0x41, 0x64, 0x64,
	0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x50, 0x0a,
	0x0e, 0x47, 0x72, 0x70, 0x63, 0x4c, 0x69, 0x73, 0x74, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x12,
	0x1e, 0x2e, 0x65, 0x74, 0x63, 0x64, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x70, 0x62, 0x2e, 0x4c, 0x69,
	0x73, 0x74, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1c, 0x2e, 0x65, 0x74, 0x63, 0x64, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x70, 0x62, 0x2e, 0x4c, 0x69,
	0x73, 0x74, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12,
	0x56, 0x0a, 0x10, 0x47, 0x72, 0x70, 0x63, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x4d, 0x65, 0x6d,
	0x62, 0x65, 0x72, 0x12, 0x20, 0x2e, 0x65, 0x74, 0x63, 0x64, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x70,
	0x62, 0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x65, 0x74, 0x63, 0x64, 0x61, 0x64, 0x6d, 0x69,
	0x6e, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x42, 0x0f, 0x5a, 0x0d, 0x2e, 0x3b, 0x65, 0x74, 0x63,
	0x64, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_etcdadmin_proto_rawDescOnce sync.Once
	file_etcdadmin_proto_rawDescData = file_etcdadmin_proto_rawDesc
)

func file_etcdadmin_proto_rawDescGZIP() []byte {
	file_etcdadmin_proto_rawDescOnce.Do(func() {
		file_etcdadmin_proto_rawDescData = protoimpl.X.CompressGZIP(file_etcdadmin_proto_rawDescData)
	})
	return file_etcdadmin_proto_rawDescData
}

var file_etcdadmin_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_etcdadmin_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_etcdadmin_proto_goTypes = []interface{}{
	(Retcode)(0),                      // 0: etcdadminpb.Retcode
	(EtcdCmd)(0),                      // 1: etcdadminpb.EtcdCmd
	(*ManagerEtcdRequest)(nil),        // 2: etcdadminpb.ManagerEtcdRequest
	(*ManagerEtcdReply)(nil),          // 3: etcdadminpb.ManagerEtcdReply
	(*AddMemberRequest)(nil),          // 4: etcdadminpb.AddMemberRequest
	(*AddMemberReply)(nil),            // 5: etcdadminpb.AddMemberReply
	(*ListMemberRequest)(nil),         // 6: etcdadminpb.ListMemberRequest
	(*ListMemberReply)(nil),           // 7: etcdadminpb.ListMemberReply
	(*RemoveMemberRequest)(nil),       // 8: etcdadminpb.RemoveMemberRequest
	(*RemoveMemberReply)(nil),         // 9: etcdadminpb.RemoveMemberReply
	(*ManagerEtcdRequest_Config)(nil), // 10: etcdadminpb.ManagerEtcdRequest.Config
	(*AddMemberRequest_Member)(nil),   // 11: etcdadminpb.AddMemberRequest.Member
	(*ListMemberReply_Member)(nil),    // 12: etcdadminpb.ListMemberReply.Member
}
var file_etcdadmin_proto_depIdxs = []int32{
	1,  // 0: etcdadminpb.ManagerEtcdRequest.cmd:type_name -> etcdadminpb.EtcdCmd
	10, // 1: etcdadminpb.ManagerEtcdRequest.cfgs:type_name -> etcdadminpb.ManagerEtcdRequest.Config
	0,  // 2: etcdadminpb.ManagerEtcdReply.errcode:type_name -> etcdadminpb.Retcode
	11, // 3: etcdadminpb.AddMemberRequest.member:type_name -> etcdadminpb.AddMemberRequest.Member
	0,  // 4: etcdadminpb.AddMemberReply.errcode:type_name -> etcdadminpb.Retcode
	0,  // 5: etcdadminpb.ListMemberReply.errcode:type_name -> etcdadminpb.Retcode
	12, // 6: etcdadminpb.ListMemberReply.members:type_name -> etcdadminpb.ListMemberReply.Member
	0,  // 7: etcdadminpb.RemoveMemberReply.errcode:type_name -> etcdadminpb.Retcode
	2,  // 8: etcdadminpb.GrpcEtcdAdmin.GrpcManagerEtcd:input_type -> etcdadminpb.ManagerEtcdRequest
	4,  // 9: etcdadminpb.GrpcEtcdAdmin.GrpcAddMember:input_type -> etcdadminpb.AddMemberRequest
	6,  // 10: etcdadminpb.GrpcEtcdAdmin.GrpcListMember:input_type -> etcdadminpb.ListMemberRequest
	8,  // 11: etcdadminpb.GrpcEtcdAdmin.GrpcRemoveMember:input_type -> etcdadminpb.RemoveMemberRequest
	3,  // 12: etcdadminpb.GrpcEtcdAdmin.GrpcManagerEtcd:output_type -> etcdadminpb.ManagerEtcdReply
	5,  // 13: etcdadminpb.GrpcEtcdAdmin.GrpcAddMember:output_type -> etcdadminpb.AddMemberReply
	7,  // 14: etcdadminpb.GrpcEtcdAdmin.GrpcListMember:output_type -> etcdadminpb.ListMemberReply
	9,  // 15: etcdadminpb.GrpcEtcdAdmin.GrpcRemoveMember:output_type -> etcdadminpb.RemoveMemberReply
	12, // [12:16] is the sub-list for method output_type
	8,  // [8:12] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_etcdadmin_proto_init() }
func file_etcdadmin_proto_init() {
	if File_etcdadmin_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_etcdadmin_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ManagerEtcdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_etcdadmin_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ManagerEtcdReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_etcdadmin_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddMemberRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_etcdadmin_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddMemberReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_etcdadmin_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListMemberRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_etcdadmin_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListMemberReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_etcdadmin_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveMemberRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_etcdadmin_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveMemberReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_etcdadmin_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ManagerEtcdRequest_Config); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_etcdadmin_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddMemberRequest_Member); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_etcdadmin_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListMemberReply_Member); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_etcdadmin_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_etcdadmin_proto_goTypes,
		DependencyIndexes: file_etcdadmin_proto_depIdxs,
		EnumInfos:         file_etcdadmin_proto_enumTypes,
		MessageInfos:      file_etcdadmin_proto_msgTypes,
	}.Build()
	File_etcdadmin_proto = out.File
	file_etcdadmin_proto_rawDesc = nil
	file_etcdadmin_proto_goTypes = nil
	file_etcdadmin_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// GrpcEtcdAdminClient is the client API for GrpcEtcdAdmin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GrpcEtcdAdminClient interface {
	// Call for private only
	GrpcManagerEtcd(ctx context.Context, in *ManagerEtcdRequest, opts ...grpc.CallOption) (*ManagerEtcdReply, error)
	GrpcAddMember(ctx context.Context, in *AddMemberRequest, opts ...grpc.CallOption) (*AddMemberReply, error)
	GrpcListMember(ctx context.Context, in *ListMemberRequest, opts ...grpc.CallOption) (*ListMemberReply, error)
	GrpcRemoveMember(ctx context.Context, in *RemoveMemberRequest, opts ...grpc.CallOption) (*RemoveMemberReply, error)
}

type grpcEtcdAdminClient struct {
	cc grpc.ClientConnInterface
}

func NewGrpcEtcdAdminClient(cc grpc.ClientConnInterface) GrpcEtcdAdminClient {
	return &grpcEtcdAdminClient{cc}
}

func (c *grpcEtcdAdminClient) GrpcManagerEtcd(ctx context.Context, in *ManagerEtcdRequest, opts ...grpc.CallOption) (*ManagerEtcdReply, error) {
	out := new(ManagerEtcdReply)
	err := c.cc.Invoke(ctx, "/etcdadminpb.GrpcEtcdAdmin/GrpcManagerEtcd", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grpcEtcdAdminClient) GrpcAddMember(ctx context.Context, in *AddMemberRequest, opts ...grpc.CallOption) (*AddMemberReply, error) {
	out := new(AddMemberReply)
	err := c.cc.Invoke(ctx, "/etcdadminpb.GrpcEtcdAdmin/GrpcAddMember", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grpcEtcdAdminClient) GrpcListMember(ctx context.Context, in *ListMemberRequest, opts ...grpc.CallOption) (*ListMemberReply, error) {
	out := new(ListMemberReply)
	err := c.cc.Invoke(ctx, "/etcdadminpb.GrpcEtcdAdmin/GrpcListMember", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grpcEtcdAdminClient) GrpcRemoveMember(ctx context.Context, in *RemoveMemberRequest, opts ...grpc.CallOption) (*RemoveMemberReply, error) {
	out := new(RemoveMemberReply)
	err := c.cc.Invoke(ctx, "/etcdadminpb.GrpcEtcdAdmin/GrpcRemoveMember", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GrpcEtcdAdminServer is the server API for GrpcEtcdAdmin service.
type GrpcEtcdAdminServer interface {
	// Call for private only
	GrpcManagerEtcd(context.Context, *ManagerEtcdRequest) (*ManagerEtcdReply, error)
	GrpcAddMember(context.Context, *AddMemberRequest) (*AddMemberReply, error)
	GrpcListMember(context.Context, *ListMemberRequest) (*ListMemberReply, error)
	GrpcRemoveMember(context.Context, *RemoveMemberRequest) (*RemoveMemberReply, error)
}

// UnimplementedGrpcEtcdAdminServer can be embedded to have forward compatible implementations.
type UnimplementedGrpcEtcdAdminServer struct {
}

func (*UnimplementedGrpcEtcdAdminServer) GrpcManagerEtcd(context.Context, *ManagerEtcdRequest) (*ManagerEtcdReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GrpcManagerEtcd not implemented")
}
func (*UnimplementedGrpcEtcdAdminServer) GrpcAddMember(context.Context, *AddMemberRequest) (*AddMemberReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GrpcAddMember not implemented")
}
func (*UnimplementedGrpcEtcdAdminServer) GrpcListMember(context.Context, *ListMemberRequest) (*ListMemberReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GrpcListMember not implemented")
}
func (*UnimplementedGrpcEtcdAdminServer) GrpcRemoveMember(context.Context, *RemoveMemberRequest) (*RemoveMemberReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GrpcRemoveMember not implemented")
}

func RegisterGrpcEtcdAdminServer(s *grpc.Server, srv GrpcEtcdAdminServer) {
	s.RegisterService(&_GrpcEtcdAdmin_serviceDesc, srv)
}

func _GrpcEtcdAdmin_GrpcManagerEtcd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ManagerEtcdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrpcEtcdAdminServer).GrpcManagerEtcd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/etcdadminpb.GrpcEtcdAdmin/GrpcManagerEtcd",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrpcEtcdAdminServer).GrpcManagerEtcd(ctx, req.(*ManagerEtcdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GrpcEtcdAdmin_GrpcAddMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddMemberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrpcEtcdAdminServer).GrpcAddMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/etcdadminpb.GrpcEtcdAdmin/GrpcAddMember",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrpcEtcdAdminServer).GrpcAddMember(ctx, req.(*AddMemberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GrpcEtcdAdmin_GrpcListMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMemberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrpcEtcdAdminServer).GrpcListMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/etcdadminpb.GrpcEtcdAdmin/GrpcListMember",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrpcEtcdAdminServer).GrpcListMember(ctx, req.(*ListMemberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GrpcEtcdAdmin_GrpcRemoveMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveMemberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrpcEtcdAdminServer).GrpcRemoveMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/etcdadminpb.GrpcEtcdAdmin/GrpcRemoveMember",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrpcEtcdAdminServer).GrpcRemoveMember(ctx, req.(*RemoveMemberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _GrpcEtcdAdmin_serviceDesc = grpc.ServiceDesc{
	ServiceName: "etcdadminpb.GrpcEtcdAdmin",
	HandlerType: (*GrpcEtcdAdminServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GrpcManagerEtcd",
			Handler:    _GrpcEtcdAdmin_GrpcManagerEtcd_Handler,
		},
		{
			MethodName: "GrpcAddMember",
			Handler:    _GrpcEtcdAdmin_GrpcAddMember_Handler,
		},
		{
			MethodName: "GrpcListMember",
			Handler:    _GrpcEtcdAdmin_GrpcListMember_Handler,
		},
		{
			MethodName: "GrpcRemoveMember",
			Handler:    _GrpcEtcdAdmin_GrpcRemoveMember_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "etcdadmin.proto",
}
